#! /usr/bin/env bash

OPTIONS="commit cleanup deploy"

select opt in $OPTIONS; do
  echo "$opt it is!"

  if [ "$opt" = "commit" ]; then
    echo Enter commit message
    read MSG
    eval "git add ."
    eval "git commit -m \"$MSG\""
    eval "git push"
    exit
  
  elif [ "$opt" = "cleanup" ]; then
    # eval "find . -name *.pyc -print0 | xargs -0 git rm"
      eval "find nestpas/ -name *.pyc -print0"
    exit
  
  fi
done
