#! /usr/bin/env bash

OPTIONS="commit cleanup deploy pep"

select opt in $OPTIONS; do
  echo "$opt it is!"

  if [ "$opt" = "commit" ]; then
    echo Enter commit message
    read MSG
    eval "git add ."
    eval "git commit -m \"$MSG\""
    eval "git push"
    exit
  
  elif [ "$opt" = "cleanup" ]; then
      echo "Cleaning up..."
      eval "find nestpas/ -name '*.pyc'"
    exit

  elif [ "$opt" = "pep" ]; then
    echo "Running pep8..."
    eval "pep8 --first nestpas/"
    exit
  
  fi
done
